/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppArchivedRouteImport } from './routes/_app/archived'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppArchivedRoute = AppArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/archived': typeof AppArchivedRoute
  '/courses': typeof AppCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/archived': typeof AppArchivedRoute
  '/courses': typeof AppCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/archived': typeof AppArchivedRoute
  '/_app/courses': typeof AppCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/archived' | '/courses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/archived' | '/courses'
  id: '__root__' | '/_app' | '/login' | '/_app/archived' | '/_app/courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archived': {
      id: '/_app/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof AppArchivedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArchivedRoute: typeof AppArchivedRoute
  AppCoursesRoute: typeof AppCoursesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchivedRoute: AppArchivedRoute,
  AppCoursesRoute: AppCoursesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
